#访问端口
server:
  port: 8764
mywebapi:
  name: EUREKA.CLIENT.FIRST.WEBAPI
#服务名称
spring:
  application:
    name: breaker.hystrix.web
  #安全认证信息
  security:
    user:
      name: admin
      password: 123456
#服务注册
eureka:
  server:
    register: localhost:8760
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.server.register}/eureka/

hystrix:
  metrics:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
