webapi: eureka.client.first.webapi
server:
  port: 8763

spring:
  application:
    name: consumer.ribbon.webapi
  #安全认证信息
  security:
    user:
      name: admin
      password: 123456

eureka:
  server:
    register: localhost:8760
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.server.register}/eureka/

