feign:
    hystrix:
      enabled: true

server:
  port: 8764

spring:
  application:
    name: consumer.feign.webapi
  #安全认证信息
  security:
    user:
      name: admin
      password: 123456

eureka:
  server:
    register: localhost:8760
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.server.register}/eureka/


