#访问端口
server:
  port: 8767
#服务名称
spring:
  application:
    name: routing.getway.web
  #安全认证信息
  security:
    user:
      name: admin
      password: 123456
  cloud:
    gateway:
      routes:
      - id: api_a_route
        #uri: http://localhost:8761
        uri: lb://EUREKA.CLIENT.FIRST.WEBAPI
        predicates:
          - Path=/api/a/**
        filters:
          - StripPrefix=2
          - name: Hystrix
            args:
              name: myerror
              fallbackUri: forward:/error
#服务注册
eureka:
  server:
    register: localhost:8760
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.server.register}/eureka/